sam_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: SAMUserBundle:Default:index }

sam_user_index:
    path:     /user/index
    defaults: { _controller: SAMUserBundle:User:index }

sam_user_add:
    path:     /user/add
    defaults: { _controller: SAMUserBundle:User:add }

sam_user_create:
    path:     /user/create
    defaults: { _controller: SAMUserBundle:User:create }
    methods: POST

sam_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: SAMUserBundle:User:edit }

sam_user_view:
    path:     /user/view/{id}
    defaults: { _controller: SAMUserBundle:User:view }

sam_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: SAMUserBundle:User:delete }

#redireccionando la ruta en caso de poner querer acceder al form create 
#redireccionamos hacia el form add
sam_user_redirect_add:
    path: /user/create
    defaults:
        _controller: SAMUserBundle:User:add
        path: /user/add
        permanent: true